import { Question, ModuleInfo } from './types';

export const modules: ModuleInfo[] = [
  {
    id: 1,
    title: 'Module 1: Networking Today',
    description: 'ประเภทการเชื่อมต่ออินเทอร์เน็ต, บทบาทของ ISP, ความเร็ว/เวลาแฝง',
    questionCount: 10,
  },
  {
    id: 3,
    title: 'Module 3: Protocols and Models',
    description: 'เลเยอร์ OSI vs TCP/IP, วัตถุประสงค์ของโปรโตคอล',
    questionCount: 10,
  },
  {
    id: 4,
    title: 'Module 4: Physical Layer',
    description: 'ประเภทสายเคเบิล, EMI/Crosstalk, Bandwidth vs Throughput vs Goodput',
    questionCount: 10,
  },
  {
    id: 5,
    title: 'Module 5: Number Systems/IP',
    description: 'CIDR notation, การคำนวณ Subnet, Host ranges',
    questionCount: 10,
  },
  {
    id: 7,
    title: 'Module 7: Ethernet Switching',
    description: 'Ethernet frames, MAC vs IP addresses, การทำงานของ Switch',
    questionCount: 10,
  },
];

export const questions: Question[] = [
  // Module 1: Networking Today
  {
    id: 'm1q1',
    module: 1,
    question: 'ข้อใดเป็นข้อดีหลักของการเชื่อมต่ออินเทอร์เน็ตแบบ Fiber-optic?',
    options: [
      'ราคาถูกที่สุดในการติดตั้ง',
      'ความเร็วสูงและไม่ถูกรบกวนจากคลื่นแม่เหล็กไฟฟ้า',
      'สามารถใช้งานได้โดยไม่ต้องมี ISP',
      'ใช้สาย Coaxial ที่มีอยู่เดิม',
    ],
    correctAnswer: 1,
    explanation: 'Fiber-optic ใช้แสงในการส่งข้อมูล ทำให้มีความเร็วสูงมากและไม่ถูกรบกวนจากคลื่น EMI (Electromagnetic Interference) เหมือนสายทองแดง',
  },
  {
    id: 'm1q2',
    module: 1,
    question: 'ISP (Internet Service Provider) มีหน้าที่อะไร?',
    options: [
      'ผลิตอุปกรณ์เครือข่าย',
      'เชื่อมต่อผู้ใช้เข้ากับอินเทอร์เน็ต',
      'สร้างเว็บไซต์ให้ผู้ใช้',
      'ติดตั้งซอฟต์แวร์ป้องกันไวรัส',
    ],
    correctAnswer: 1,
    explanation: 'ISP (Internet Service Provider) คือผู้ให้บริการอินเทอร์เน็ต ทำหน้าที่เชื่อมต่อผู้ใช้ (บ้านหรือธุรกิจ) เข้ากับเครือข่ายอินเทอร์เน็ต',
  },
  {
    id: 'm1q3',
    module: 1,
    question: 'Latency (เวลาแฝง) หมายถึงอะไร?',
    options: [
      'จำนวนข้อมูลที่สามารถส่งได้ต่อวินาที',
      'เวลาที่ข้อมูลใช้ในการเดินทางจากต้นทางไปยังปลายทาง',
      'ความถี่ของสัญญาณที่ส่ง',
      'ขนาดของ Packet ที่ส่ง',
    ],
    correctAnswer: 1,
    explanation: 'Latency คือเวลาที่ข้อมูลใช้ในการเดินทางจากจุดหนึ่งไปยังอีกจุดหนึ่ง โดยทั่วไปวัดเป็น milliseconds (ms) ยิ่ง latency ต่ำยิ่งดี',
  },
  {
    id: 'm1q4',
    module: 1,
    question: 'การเชื่อมต่อแบบ DSL ใช้สายประเภทใด?',
    options: [
      'สาย Fiber-optic',
      'สายโทรศัพท์ (Telephone line)',
      'สาย Coaxial',
      'สาย Ethernet',
    ],
    correctAnswer: 1,
    explanation: 'DSL (Digital Subscriber Line) ใช้สายโทรศัพท์เดิมที่มีอยู่แล้วในการส่งข้อมูลอินเทอร์เน็ต โดยใช้ความถี่ที่แตกต่างจากเสียงโทรศัพท์',
  },
  {
    id: 'm1q5',
    module: 1,
    question: 'ข้อใดถูกต้องเกี่ยวกับ Bandwidth?',
    options: [
      'Bandwidth คือความเร็วจริงที่ได้รับ',
      'Bandwidth คือความจุสูงสุดในการส่งข้อมูล',
      'Bandwidth เท่ากับ Latency',
      'Bandwidth วัดเป็น milliseconds',
    ],
    correctAnswer: 1,
    explanation: 'Bandwidth คือความจุสูงสุด (maximum capacity) ในการส่งข้อมูลผ่านลิงก์เครือข่าย วัดเป็น bits per second (bps) เช่น 100 Mbps',
  },
  {
    id: 'm1q6',
    module: 1,
    question: 'การเชื่อมต่อแบบ Dial-up มีลักษณะอย่างไร?',
    options: [
      'ความเร็วสูงและเป็นแบบ always-on',
      'ราคาถูกแต่ Bandwidth ต่ำมาก',
      'ใช้สาย Fiber-optic',
      'เหมาะกับการใช้งานในองค์กรใหญ่',
    ],
    correctAnswer: 1,
    explanation: 'Dial-up Telephone มีราคาถูกแต่ Bandwidth ต่ำมาก ใช้โมเด็มหมุนโทรศัพท์ ไม่ใช่แบบ always-on',
  },
  {
    id: 'm1q7',
    module: 1,
    question: 'การเชื่อมต่อแบบ Cable Internet ใช้สายประเภทใด?',
    options: [
      'สายโทรศัพท์',
      'สาย Coaxial (สายเคเบิลทีวี)',
      'สาย Fiber-optic',
      'สาย UTP',
    ],
    correctAnswer: 1,
    explanation: 'Cable Internet ใช้สาย Coaxial ซึ่งเป็นสายเคเบิลทีวีที่มีอยู่เดิม มี Bandwidth สูงและเป็นแบบ always-on',
  },
  {
    id: 'm1q8',
    module: 1,
    question: 'การเชื่อมต่อแบบ Satellite เหมาะกับพื้นที่แบบใด?',
    options: [
      'ในเมืองใหญ่',
      'ในอาคารสำนักงาน',
      'พื้นที่ชนบทที่ไม่มีสายเข้าถึง',
      'ในโรงงานอุตสาหกรรม',
    ],
    correctAnswer: 2,
    explanation: 'Satellite Internet เหมาะสำหรับพื้นที่ชนบทหรือพื้นที่ห่างไกลที่ไม่มีโครงสร้างพื้นฐานแบบสาย (Wired) เข้าถึง',
  },
  {
    id: 'm1q9',
    module: 1,
    question: 'SOHO (Small Office/Home Office) หมายถึงอะไร?',
    options: [
      'เครือข่ายขนาดใหญ่ในองค์กร',
      'เครือข่ายขนาดเล็กที่เชื่อมคอมพิวเตอร์ไม่กี่เครื่อง',
      'ศูนย์ข้อมูลของบริษัท',
      'เครือข่ายระดับประเทศ',
    ],
    correctAnswer: 1,
    explanation: 'SOHO (Small Office/Home Office) คือเครือข่ายขนาดเล็กที่เชื่อมคอมพิวเตอร์ไม่กี่เครื่องเข้าด้วยกันและออกสู่อินเทอร์เน็ต',
  },
  {
    id: 'm1q10',
    module: 1,
    question: 'หากไม่มี ISP จะเกิดอะไรขึ้น?',
    options: [
      'อุปกรณ์ใน LAN ไม่สามารถสื่อสารกันได้',
      'อุปกรณ์ใน LAN ไม่สามารถเข้าถึงอินเทอร์เน็ตได้',
      'คอมพิวเตอร์ไม่สามารถเปิดได้',
      'ไม่มีผลกระทบใดๆ',
    ],
    correctAnswer: 1,
    explanation: 'หากไม่มี ISP อุปกรณ์ต่างๆ ใน LAN จะสื่อสารกันเองได้ แต่ไม่สามารถเข้าถึง World Wide Web หรือเครือข่ายภายนอกได้',
  },

  // Module 3: Protocols and Models
  {
    id: 'm3q1',
    module: 3,
    question: 'OSI Model มีกี่เลเยอร์?',
    options: ['4 เลเยอร์', '5 เลเยอร์', '6 เลเยอร์', '7 เลเยอร์'],
    correctAnswer: 3,
    explanation: 'OSI (Open Systems Interconnection) Model มี 7 เลเยอร์: Physical, Data Link, Network, Transport, Session, Presentation, Application',
  },
  {
    id: 'm3q2',
    module: 3,
    question: 'TCP/IP Model มีกี่เลเยอร์?',
    options: ['3 เลเยอร์', '4 เลเยอร์', '5 เลเยอร์', '7 เลเยอร์'],
    correctAnswer: 1,
    explanation: 'TCP/IP Model มี 4 เลเยอร์: Network Access (หรือ Link), Internet, Transport, Application',
  },
  {
    id: 'm3q3',
    module: 3,
    question: 'เลเยอร์ใดใน OSI Model รับผิดชอบการ Routing?',
    options: ['Physical Layer', 'Data Link Layer', 'Network Layer', 'Transport Layer'],
    correctAnswer: 2,
    explanation: 'Network Layer (เลเยอร์ 3) รับผิดชอบการ Routing หรือการหาเส้นทางที่ดีที่สุดในการส่ง Packet ไปยังปลายทาง โดยใช้ IP Address',
  },
  {
    id: 'm3q4',
    module: 3,
    question: 'Application Layer ใน TCP/IP Model เทียบเท่ากับกี่เลเยอร์ใน OSI?',
    options: ['1 เลเยอร์', '2 เลเยอร์', '3 เลเยอร์', '4 เลเยอร์'],
    correctAnswer: 2,
    explanation: 'Application Layer ใน TCP/IP Model เทียบเท่ากับ 3 เลเยอร์บนใน OSI คือ Application, Presentation, Session',
  },
  {
    id: 'm3q5',
    module: 3,
    question: 'Transport Layer ใน TCP/IP ใช้โปรโตคอลอะไร?',
    options: ['IP', 'HTTP', 'TCP และ UDP', 'Ethernet'],
    correctAnswer: 2,
    explanation: 'Transport Layer ใช้โปรโตคอล TCP (Connection-oriented) และ UDP (Connectionless) ในการสื่อสารระหว่างอุปกรณ์',
  },
  {
    id: 'm3q6',
    module: 3,
    question: 'Internet Layer ใน TCP/IP ใช้โปรโตคอลอะไร?',
    options: ['TCP', 'UDP', 'IP', 'HTTP'],
    correctAnswer: 2,
    explanation: 'Internet Layer ใช้โปรโตคอล IP (Internet Protocol) ในการหาเส้นทางที่ดีที่สุดสำหรับการส่งข้อมูล',
  },
  {
    id: 'm3q7',
    module: 3,
    question: 'Physical Layer (เลเยอร์ 1) ใน OSI ทำหน้าที่อะไร?',
    options: [
      'การ Routing ข้ามเครือข่าย',
      'การส่งสัญญาณทางไฟฟ้า/แสง (Bits)',
      'การแลกเปลี่ยนเฟรมบนสื่อ',
      'การสื่อสาร process-to-process',
    ],
    correctAnswer: 1,
    explanation: 'Physical Layer (เลเยอร์ 1) รับผิดชอบการส่งสัญญาณทางไฟฟ้าหรือแสง (Bits) ผ่านสื่อนำสัญญาณ',
  },
  {
    id: 'm3q8',
    module: 3,
    question: 'Presentation Layer (เลเยอร์ 6) ใน OSI ทำหน้าที่อะไร?',
    options: [
      'การ Routing ข้ามเครือข่าย',
      'การส่งสัญญาณทางไฟฟ้า',
      'รูปแบบข้อมูล (Data Representation)',
      'การสื่อสาร process-to-process',
    ],
    correctAnswer: 2,
    explanation: 'Presentation Layer (เลเยอร์ 6) รับผิดชอบรูปแบบข้อมูล (Representation) การเข้ารหัส และการบีบอัดข้อมูล',
  },
  {
    id: 'm3q9',
    module: 3,
    question: 'ข้อดีของการใช้ Layered Model คืออะไร?',
    options: [
      'ทำให้เครือข่ายช้าลง',
      'ป้องกันการเปลี่ยนแปลงเทคโนโลยีในชั้นหนึ่งส่งผลกระทบต่อชั้นอื่น',
      'ทำให้ต้องใช้อุปกรณ์จากยี่ห้อเดียวกันเท่านั้น',
      'ลดจำนวนโปรโตคอลที่ต้องใช้',
    ],
    correctAnswer: 1,
    explanation: 'Layered Model ช่วยให้การเปลี่ยนแปลงเทคโนโลยีในชั้นหนึ่งไม่ส่งผลกระทบต่อชั้นอื่น (Independence) และช่วยให้ผลิตภัณฑ์จากต่างยี่ห้อทำงานร่วมกันได้',
  },
  {
    id: 'm3q10',
    module: 3,
    question: 'ข้อแตกต่างสำคัญระหว่าง OSI และ TCP/IP คืออะไร?',
    options: [
      'OSI ใช้งานจริงบนอินเทอร์เน็ต',
      'TCP/IP มี 7 เลเยอร์',
      'OSI แยก Layer ล่างสุดเป็น Data Link และ Physical แต่ TCP/IP รวมเป็น Network Access',
      'TCP/IP ไม่มี Transport Layer',
    ],
    correctAnswer: 2,
    explanation: 'OSI แยก Layer ล่างสุดเป็น Data Link และ Physical ในขณะที่ TCP/IP รวมเป็นชั้นเดียวคือ Network Access และ OSI แยก Layer บนเป็น Application, Presentation, Session แต่ TCP/IP รวมเป็น Application',
  },

  // Module 4: Physical Layer
  {
    id: 'm4q1',
    module: 4,
    question: 'สาย UTP มีข้อดีอะไร?',
    options: [
      'ป้องกัน EMI ได้ดีที่สุด',
      'ราคาถูก ติดตั้งง่าย นิยมใช้มากที่สุด',
      'ส่งได้ระยะทางไกลที่สุด',
      'ใช้แสงในการส่งข้อมูล',
    ],
    correctAnswer: 1,
    explanation: 'UTP (Unshielded Twisted Pair) เป็นสายทองแดงเกลียวคู่ ราคาถูก ติดตั้งง่าย และนิยมใช้มากที่สุด',
  },
  {
    id: 'm4q2',
    module: 4,
    question: 'EMI (Electromagnetic Interference) ส่งผลกระทบต่อสายประเภทใดมากที่สุด?',
    options: ['Fiber-optic', 'สายทองแดง (Copper)', 'ไม่มีสายใดได้รับผลกระทบ', 'สายทุกประเภทได้รับผลกระทบเท่ากัน'],
    correctAnswer: 1,
    explanation: 'สายทองแดง (เช่น UTP, STP, Coaxial) ได้รับผลกระทบจาก EMI มากที่สุด เพราะใช้สัญญาณไฟฟ้า ส่วน Fiber-optic ใช้แสงจึงไม่ถูกรบกวน',
  },
  {
    id: 'm4q3',
    module: 4,
    question: 'Crosstalk คืออะไร?',
    options: [
      'การรบกวนจากสัญญาณสายข้างเคียง',
      'การสูญเสียสัญญาณเมื่อระยะทางไกล',
      'การเข้ารหัสข้อมูล',
      'ความเร็วในการส่งข้อมูล',
    ],
    correctAnswer: 0,
    explanation: 'Crosstalk คือการรบกวนที่เกิดขึ้นเมื่อสัญญาณจากสายหนึ่งรบกวนสายที่อยู่ใกล้เคียง การบิดคู่สาย (Twisted Pair) ช่วยลด Crosstalk ได้',
  },
  {
    id: 'm4q4',
    module: 4,
    question: 'ความแตกต่างระหว่าง Throughput และ Goodput คืออะไร?',
    options: [
      'ไม่มีความแตกต่าง',
      'Throughput รวม Overhead, Goodput คือข้อมูลที่ใช้งานได้จริง',
      'Goodput มากกว่า Throughput เสมอ',
      'Throughput วัดเป็น ms, Goodput วัดเป็น bps',
    ],
    correctAnswer: 1,
    explanation: 'Throughput คือปริมาณข้อมูลทั้งหมดที่ส่งได้ (รวม Header/Overhead) ส่วน Goodput คือปริมาณข้อมูลที่ใช้งานได้จริง (เฉพาะ Payload) Goodput จึงน้อยกว่า Throughput',
  },
  {
    id: 'm4q5',
    module: 4,
    question: 'ข้อดีของ Fiber Optic เมื่อเทียบกับสายทองแดงคืออะไร?',
    options: [
      'ราคาถูกกว่า',
      'ติดตั้งง่ายกว่า',
      'ส่งได้ไกลกว่า Bandwidth สูงกว่า และไม่ถูก EMI รบกวน',
      'ใช้ไฟฟ้าน้อยกว่า',
    ],
    correctAnswer: 2,
    explanation: 'Fiber Optic ทำจากแก้ว ใช้แสงส่งข้อมูล มีข้อดีคือส่งได้ไกลกว่า Bandwidth สูงกว่า และป้องกัน EMI/RFI ได้สมบูรณ์',
  },
  {
    id: 'm4q6',
    module: 4,
    question: 'วิธีแก้ไขปัญหา EMI คืออะไร?',
    options: [
      'ใช้สาย UTP',
      'ใช้สาย STP หรือ Fiber Optic',
      'เพิ่มความยาวสาย',
      'ลด Bandwidth',
    ],
    correctAnswer: 1,
    explanation: 'ใช้สาย STP ที่มีฟอยล์หุ้มเพื่อกัน EMI หรือใช้ Fiber Optic เพื่อตัดปัญหา EMI โดยสิ้นเชิงเพราะใช้แสง',
  },
  {
    id: 'm4q7',
    module: 4,
    question: 'สาย UTP ย่อมาจากอะไร?',
    options: [
      'Universal Twisted Pair',
      'Unshielded Twisted Pair',
      'Ultra Thin Protocol',
      'Unified Transfer Protocol',
    ],
    correctAnswer: 1,
    explanation: 'UTP ย่อมาจาก Unshielded Twisted Pair คือสายทองแดงเกลียวคู่ที่ไม่มีฉนวนหุ้มป้องกันสัญญาณรบกวนภายนอก',
  },
  {
    id: 'm4q8',
    module: 4,
    question: 'สาย STP ต่างจาก UTP อย่างไร?',
    options: [
      'STP เร็วกว่า',
      'STP มีฟอยล์หุ้มป้องกัน EMI/RFI',
      'STP ใช้แสงส่งข้อมูล',
      'STP ราคาถูกกว่า',
    ],
    correctAnswer: 1,
    explanation: 'STP (Shielded Twisted Pair) มีฟอยล์หุ้มเพื่อป้องกันสัญญาณรบกวน EMI/RFI ได้ดีกว่า UTP แต่ราคาแพงและติดตั้งยากกว่า',
  },
  {
    id: 'm4q9',
    module: 4,
    question: 'การบิดเกลียวสาย (Twisting) ในสาย UTP ช่วยลดปัญหาใด?',
    options: [
      'ลด Bandwidth',
      'ลด Crosstalk',
      'ลดความเร็ว',
      'ลดระยะทาง',
    ],
    correctAnswer: 1,
    explanation: 'การบิดเกลียวสาย (Twisting) ช่วยลดการรบกวนแบบ Crosstalk ซึ่งเป็นสัญญาณรบกวนข้ามคู่สาย',
  },
  {
    id: 'm4q10',
    module: 4,
    question: '1 Gbps เท่ากับกี่ Mbps?',
    options: ['100 Mbps', '500 Mbps', '1000 Mbps', '10000 Mbps'],
    correctAnswer: 2,
    explanation: '1 Gbps = 1000 Mbps (10^9 bits per second = 10^3 × 10^6 bits per second)',
  },

  // Module 5: Number Systems/IP
  {
    id: 'm5q1',
    module: 5,
    question: 'IP Address 192.168.1.0/24 มี Host Address ใช้งานได้กี่ตัว?',
    options: ['254', '255', '256', '252'],
    correctAnswer: 0,
    explanation: '/24 หมายถึง 8 bits สำหรับ Host (32-24=8) ทำให้มี 2^8 = 256 addresses แต่ต้องหัก Network Address และ Broadcast Address ออก เหลือ 254 ตัว',
  },
  {
    id: 'm5q2',
    module: 5,
    question: 'เลขฐานสอง 11001010 เท่ากับเลขฐานสิบเท่าไหร่?',
    options: ['192', '200', '202', '210'],
    correctAnswer: 2,
    explanation: '11001010 = 128+64+0+0+8+0+2+0 = 202 (ใช้ค่าประจำหลัก 128, 64, 32, 16, 8, 4, 2, 1)',
  },
  {
    id: 'm5q3',
    module: 5,
    question: 'Subnet Mask 255.255.255.240 เทียบเท่ากับ CIDR notation ใด?',
    options: ['/24', '/26', '/28', '/30'],
    correctAnswer: 2,
    explanation: '255.255.255.240 → 240 = 128+64+32+16 = 4 บิต หลัง /24 ดังนั้น /24 + 4 = /28',
  },
  {
    id: 'm5q4',
    module: 5,
    question: 'สูตรคำนวณจำนวน Host ที่ใช้งานได้คือข้อใด?',
    options: [
      '2^h',
      '2^h - 1',
      '2^h - 2',
      '2^(32-h)',
    ],
    correctAnswer: 2,
    explanation: 'สูตรคำนวณจำนวน Host = 2^h - 2 โดย h คือจำนวน host bits ลบ 2 เพราะต้องหัก Network Address และ Broadcast Address ออก',
  },
  {
    id: 'm5q5',
    module: 5,
    question: 'เครือข่าย 10.0.0.0/8 มี Subnet Mask เท่ากับเท่าไหร่?',
    options: ['255.0.0.0', '255.255.0.0', '255.255.255.0', '255.255.255.255'],
    correctAnswer: 0,
    explanation: '/8 หมายถึง 8 บิตแรกเป็น Network portion ดังนั้น Subnet Mask = 255.0.0.0',
  },
  {
    id: 'm5q6',
    module: 5,
    question: 'หาก IP Address คือ 192.168.10.65/26 Broadcast Address คืออะไร?',
    options: ['192.168.10.127', '192.168.10.63', '192.168.10.255', '192.168.10.64'],
    correctAnswer: 0,
    explanation: '/26 มี Block Size = 64 (2^6) IP 65 อยู่ในก้อน 64-127 ดังนั้น Broadcast = 192.168.10.127',
  },
  {
    id: 'm5q7',
    module: 5,
    question: '/26 มี Block Size (Magic Number) เท่าไหร่?',
    options: ['32', '64', '128', '256'],
    correctAnswer: 1,
    explanation: '/26 มี 6 host bits (32-26=6) ดังนั้น Block Size = 2^6 = 64',
  },
  {
    id: 'm5q8',
    module: 5,
    question: 'หากต้องการรองรับ 500 Hosts ต้องใช้ Prefix ใด?',
    options: ['/22', '/23', '/24', '/25'],
    correctAnswer: 1,
    explanation: 'ต้องการ 500+2 = 502 addresses, 2^9 = 512 (พอดี) ดังนั้น host bits = 9, Prefix = 32-9 = /23',
  },
  {
    id: 'm5q9',
    module: 5,
    question: 'IP Address 192.168.10.70/26 มี Network Address คืออะไร?',
    options: ['192.168.10.0', '192.168.10.64', '192.168.10.70', '192.168.10.128'],
    correctAnswer: 1,
    explanation: '/26 มี Block Size = 64 ท่องแม่ 64: 0, 64, 128... เลข 70 อยู่ระหว่าง 64-127 ดังนั้น Network Address = 192.168.10.64',
  },
  {
    id: 'm5q10',
    module: 5,
    question: '/27 มี Subnet Mask (Octet สุดท้าย) เท่าไหร่?',
    options: ['192', '224', '240', '248'],
    correctAnswer: 1,
    explanation: '/27 = /24 + 3 bits ยืมมา 3 บิต = 128+64+32 = 224 ดังนั้น Subnet Mask = 255.255.255.224',
  },

  // Module 7: Ethernet Switching
  {
    id: 'm7q1',
    module: 7,
    question: 'Ethernet Frame ประกอบด้วยฟิลด์ใดบ้าง?',
    options: [
      'IP Source, IP Destination, Data',
      'Destination MAC, Source MAC, Type/Length, Data, FCS',
      'Port Number, Sequence Number, Data',
      'Header, Payload, Checksum',
    ],
    correctAnswer: 1,
    explanation: 'Ethernet Frame ประกอบด้วยฟิลด์สำคัญ: Destination MAC, Source MAC, Type/Length, Data, FCS (ตรวจสอบความถูกต้อง)',
  },
  {
    id: 'm7q2',
    module: 7,
    question: 'Switch ใช้ข้อมูลใดในการ Forward frame?',
    options: ['IP Address', 'MAC Address', 'Port Number', 'Protocol Type'],
    correctAnswer: 1,
    explanation: 'Switch ทำงานที่ Layer 2 (Data Link) จึงใช้ MAC Address ในการตัดสินใจว่าจะส่ง Frame ออกทาง Port ใด โดยดูจาก MAC Address Table',
  },
  {
    id: 'm7q3',
    module: 7,
    question: 'เมื่อ Switch ไม่พบ Destination MAC ใน MAC Address Table จะทำอย่างไร?',
    options: [
      'Drop frame ทิ้ง',
      'ส่งกลับไปยังต้นทาง',
      'Flood ออกทุก Port ยกเว้น Port ต้นทาง',
      'ส่งไปยัง Default Gateway',
    ],
    correctAnswer: 2,
    explanation: 'เมื่อไม่รู้จัก Destination MAC (Unknown Unicast) Switch จะ Flood frame ออกไปทุก Port ยกเว้น Port ที่ได้รับ frame มา',
  },
  {
    id: 'm7q4',
    module: 7,
    question: 'FCS (Frame Check Sequence) ใน Ethernet Frame ไว้ทำอะไร?',
    options: [
      'ระบุความยาวของ Frame',
      'ตรวจสอบข้อผิดพลาดของข้อมูล',
      'ระบุประเภทของ Protocol',
      'เก็บ MAC Address ปลายทาง',
    ],
    correctAnswer: 1,
    explanation: 'FCS (Frame Check Sequence) ใช้ CRC (Cyclic Redundancy Check) เพื่อตรวจสอบว่า Frame ได้รับความเสียหายระหว่างการส่งหรือไม่',
  },
  {
    id: 'm7q5',
    module: 7,
    question: 'MAC Address ใช้สำหรับอะไร?',
    options: [
      'ระบุเส้นทางข้ามเครือข่าย (End-to-End)',
      'สื่อสารระหว่างอุปกรณ์ในเครือข่ายเดียวกัน (Local Network)',
      'เข้ารหัสข้อมูล',
      'บีบอัดข้อมูล',
    ],
    correctAnswer: 1,
    explanation: 'MAC Address (Layer 2) ใช้สำหรับการสื่อสารทางกายภาพระหว่างอุปกรณ์ในเครือข่ายเดียวกัน (Local Network)',
  },
  {
    id: 'm7q6',
    module: 7,
    question: 'IP Address ต่างจาก MAC Address อย่างไร?',
    options: [
      'IP ใช้ใน Local Network, MAC ใช้ข้ามเครือข่าย',
      'IP ใช้ระบุเส้นทาง End-to-End, MAC ใช้ในเครือข่ายเดียวกัน',
      'IP และ MAC ทำหน้าที่เหมือนกัน',
      'MAC มีขนาด 32 bits, IP มีขนาด 48 bits',
    ],
    correctAnswer: 1,
    explanation: 'IP Address (Layer 3) ใช้ระบุเส้นทางทางตรรกะ End-to-End ข้ามเครือข่าย ส่วน MAC Address (Layer 2) ใช้สื่อสารในเครือข่ายเดียวกัน',
  },
  {
    id: 'm7q7',
    module: 7,
    question: 'Switch เรียนรู้ MAC Address จากส่วนใดของ Frame?',
    options: [
      'Destination MAC',
      'Source MAC',
      'FCS',
      'Type/Length',
    ],
    correctAnswer: 1,
    explanation: 'Switch เรียนรู้ (Learning) โดยดูที่ Source MAC Address ของ Frame ที่เข้ามา แล้วบันทึกลงใน MAC Address Table คู่กับ Port ที่รับเข้ามา',
  },
  {
    id: 'm7q8',
    module: 7,
    question: 'ขนาดของ Ethernet Frame อยู่ในช่วงใด?',
    options: ['32-512 bytes', '64-1518 bytes', '128-2048 bytes', '256-4096 bytes'],
    correctAnswer: 1,
    explanation: 'Ethernet Frame มีขนาดต่ำสุด 64 bytes และสูงสุด 1518 bytes',
  },
  {
    id: 'm7q9',
    module: 7,
    question: 'เมื่อส่งข้อมูลข้ามเครือข่าย ค่าใดจะเปลี่ยนในแต่ละ Hop?',
    options: [
      'IP Address ต้นทาง',
      'IP Address ปลายทาง',
      'MAC Address',
      'ทั้ง IP และ MAC',
    ],
    correctAnswer: 2,
    explanation: 'เมื่อส่งข้อมูลข้ามเครือข่าย IP Address จะคงเดิมตลอดเส้นทาง แต่ MAC Address จะเปลี่ยนไปในแต่ละ Hop (จาก Router ตัวหนึ่งไปยังอีกตัว)',
  },
  {
    id: 'm7q10',
    module: 7,
    question: 'Switch ตัดสินใจส่ง Frame ออกโดยดูจากอะไร?',
    options: [
      'Source MAC Address',
      'Destination MAC Address',
      'IP Address',
      'FCS',
    ],
    correctAnswer: 1,
    explanation: 'Switch จะดูที่ Destination MAC Address เพื่อตัดสินใจส่งออก ถ้ามีในตารางส่งเฉพาะ Port นั้น ถ้าไม่มีจะ Flood ออกทุก Port',
  },
];

export const getQuestionsByModules = (moduleIds: number[]): Question[] => {
  return questions.filter((q) => moduleIds.includes(q.module));
};

export const shuffleQuestions = (questions: Question[]): Question[] => {
  const shuffled = [...questions];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};
